/**
 * Набор иконок для писем.
 *
 * Файл собран скриптом backend/scripts/buildEmailIcons.js из lucide-react —
 * руками его не правят: следующая сборка сотрёт правку. Чтобы добавить иконку,
 * допишите её в список в скрипте и запустите его заново.
 */

import {
  HeartPulse,
  Stethoscope,
  Activity,
  Pill,
  Syringe,
  TestTube,
  TestTubes,
  Microscope,
  Thermometer,
  Scan,
  Dna,
  Brain,
  Eye,
  Ear,
  Bone,
  Baby,
  Cross,
  Briefcase,
  Bed,
  Accessibility,
  Dumbbell,
  Salad,
  Weight,
  Droplet,
  CalendarCheck,
  CalendarDays,
  CalendarClock,
  CalendarPlus,
  Clock,
  Timer,
  Hourglass,
  AlarmClock,
  BadgePercent,
  Percent,
  Tag,
  Tags,
  Gift,
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  PiggyBank,
  Receipt,
  Ticket,
  Phone,
  PhoneCall,
  Smartphone,
  Mail,
  MessageCircle,
  MessagesSquare,
  Send,
  Bell,
  Headphones,
  Globe,
  QrCode,
  MapPin,
  Map,
  Building2,
  Home,
  Navigation,
  Car,
  Bus,
  ParkingCircle,
  User,
  Users,
  UserCheck,
  UserPlus,
  HeartHandshake,
  GraduationCap,
  Award,
  BadgeCheck,
  Star,
  ThumbsUp,
  Smile,
  Crown,
  FileText,
  ClipboardList,
  ClipboardCheck,
  FileCheck,
  BookOpen,
  Folder,
  Download,
  Printer,
  Check,
  CheckCircle2,
  Info,
  ShieldCheck,
  Shield,
  Zap,
  Lightbulb,
  Target,
  TrendingUp,
  Sparkles,
  Rocket,
  Leaf,
  Sun,
  Snowflake,
  Flame,
  Truck,
  Package,
  Search,
  Camera,
  Video,
  Play,
  Lock,
  Key,
  Flag,
  Compass,
  Gem,
  Coffee,
} from 'lucide-react';

export const ICON_GROUPS = [
  ['med', "Медицина"],
  ['time', "Время и запись"],
  ['money', "Цены и акции"],
  ['contact', "Связь"],
  ['place', "Адрес и дорога"],
  ['people', "Люди"],
  ['docs', "Документы"],
  ['misc', "Знаки"],
];

export const EMAIL_ICONS = [
  { key: 'heart-pulse', Icon: HeartPulse, group: 'med', label: "Пульс", keywords: "сердце кардио пульс экг диагностика" },
  { key: 'stethoscope', Icon: Stethoscope, group: 'med', label: "Стетоскоп", keywords: "врач терапевт приём осмотр" },
  { key: 'activity', Icon: Activity, group: 'med', label: "Кардиограмма", keywords: "экг пульс график показатели" },
  { key: 'pill', Icon: Pill, group: 'med', label: "Таблетка", keywords: "лекарство препарат аптека лечение" },
  { key: 'syringe', Icon: Syringe, group: 'med', label: "Шприц", keywords: "укол прививка вакцина инъекция капельница" },
  { key: 'test-tube', Icon: TestTube, group: 'med', label: "Пробирка", keywords: "анализ лаборатория кровь забор" },
  { key: 'test-tubes', Icon: TestTubes, group: 'med', label: "Пробирки", keywords: "анализы лаборатория комплекс чекап" },
  { key: 'microscope', Icon: Microscope, group: 'med', label: "Микроскоп", keywords: "лаборатория исследование гистология" },
  { key: 'thermometer', Icon: Thermometer, group: 'med', label: "Градусник", keywords: "температура жар простуда" },
  { key: 'scan', Icon: Scan, group: 'med', label: "Снимок", keywords: "мрт кт узи рентген томография диагностика" },
  { key: 'dna', Icon: Dna, group: 'med', label: "ДНК", keywords: "генетика анализ наследственность" },
  { key: 'brain', Icon: Brain, group: 'med', label: "Мозг", keywords: "невролог голова мрт память" },
  { key: 'eye', Icon: Eye, group: 'med', label: "Глаз", keywords: "окулист офтальмолог зрение" },
  { key: 'ear', Icon: Ear, group: 'med', label: "Ухо", keywords: "лор отоларинголог слух" },
  { key: 'bone', Icon: Bone, group: 'med', label: "Кость", keywords: "травматолог ортопед перелом суставы" },
  { key: 'baby', Icon: Baby, group: 'med', label: "Малыш", keywords: "педиатр ребёнок дети грудничок" },
  { key: 'cross', Icon: Cross, group: 'med', label: "Крест", keywords: "медицина помощь клиника" },
  { key: 'briefcase', Icon: Briefcase, group: 'med', label: "Чемоданчик", keywords: "врач выезд на дом помощь" },
  { key: 'bed', Icon: Bed, group: 'med', label: "Койка", keywords: "стационар палата дневной госпитализация" },
  { key: 'accessibility', Icon: Accessibility, group: 'med', label: "Реабилитация", keywords: "доступность инвалид восстановление" },
  { key: 'dumbbell', Icon: Dumbbell, group: 'med', label: "Гантель", keywords: "лфк спорт реабилитация физкультура" },
  { key: 'salad', Icon: Salad, group: 'med', label: "Питание", keywords: "диетолог еда рацион похудение" },
  { key: 'weight', Icon: Weight, group: 'med', label: "Вес", keywords: "диетолог похудение весы килограммы" },
  { key: 'droplet', Icon: Droplet, group: 'med', label: "Капля", keywords: "кровь анализ гемоглобин капельница" },
  { key: 'calendar-check', Icon: CalendarCheck, group: 'time', label: "Запись", keywords: "календарь записаться приём подтверждено" },
  { key: 'calendar-days', Icon: CalendarDays, group: 'time', label: "Календарь", keywords: "дни расписание график" },
  { key: 'calendar-clock', Icon: CalendarClock, group: 'time', label: "Время приёма", keywords: "календарь часы расписание" },
  { key: 'calendar-plus', Icon: CalendarPlus, group: 'time', label: "Новая запись", keywords: "календарь добавить записаться" },
  { key: 'clock', Icon: Clock, group: 'time', label: "Часы", keywords: "время режим работы длительность" },
  { key: 'timer', Icon: Timer, group: 'time', label: "Секундомер", keywords: "быстро срочно минуты результат" },
  { key: 'hourglass', Icon: Hourglass, group: 'time', label: "Песочные часы", keywords: "ожидание срок подготовка" },
  { key: 'alarm-clock', Icon: AlarmClock, group: 'time', label: "Будильник", keywords: "напоминание не забыть время" },
  { key: 'badge-percent', Icon: BadgePercent, group: 'money', label: "Скидка", keywords: "процент акция выгода распродажа" },
  { key: 'percent', Icon: Percent, group: 'money', label: "Процент", keywords: "скидка акция выгода" },
  { key: 'tag', Icon: Tag, group: 'money', label: "Ценник", keywords: "цена стоимость акция" },
  { key: 'tags', Icon: Tags, group: 'money', label: "Ценники", keywords: "цены прайс стоимость" },
  { key: 'gift', Icon: Gift, group: 'money', label: "Подарок", keywords: "акция бонус сюрприз подарочный" },
  { key: 'wallet', Icon: Wallet, group: 'money', label: "Кошелёк", keywords: "оплата деньги цена рассрочка" },
  { key: 'credit-card', Icon: CreditCard, group: 'money', label: "Карта", keywords: "оплата банк рассрочка безнал" },
  { key: 'banknote', Icon: Banknote, group: 'money', label: "Деньги", keywords: "оплата наличные рубли цена" },
  { key: 'coins', Icon: Coins, group: 'money', label: "Монеты", keywords: "деньги цена накопить бонусы" },
  { key: 'piggy-bank', Icon: PiggyBank, group: 'money', label: "Копилка", keywords: "экономия выгода накопления" },
  { key: 'receipt', Icon: Receipt, group: 'money', label: "Чек", keywords: "оплата квитанция налоговый вычет" },
  { key: 'ticket', Icon: Ticket, group: 'money', label: "Купон", keywords: "промокод сертификат акция" },
  { key: 'phone', Icon: Phone, group: 'contact', label: "Телефон", keywords: "позвонить номер связь" },
  { key: 'phone-call', Icon: PhoneCall, group: 'contact', label: "Звонок", keywords: "позвонить колл-центр связь" },
  { key: 'smartphone', Icon: Smartphone, group: 'contact', label: "Смартфон", keywords: "телефон приложение мобильное" },
  { key: 'mail', Icon: Mail, group: 'contact', label: "Почта", keywords: "письмо email адрес" },
  { key: 'message-circle', Icon: MessageCircle, group: 'contact', label: "Сообщение", keywords: "чат написать мессенджер" },
  { key: 'messages-square', Icon: MessagesSquare, group: 'contact', label: "Переписка", keywords: "чат диалог поддержка" },
  { key: 'send', Icon: Send, group: 'contact', label: "Отправить", keywords: "телеграм сообщение" },
  { key: 'bell', Icon: Bell, group: 'contact', label: "Уведомление", keywords: "напоминание оповещение звонок" },
  { key: 'headphones', Icon: Headphones, group: 'contact', label: "Поддержка", keywords: "колл-центр оператор наушники" },
  { key: 'globe', Icon: Globe, group: 'contact', label: "Сайт", keywords: "интернет онлайн веб" },
  { key: 'qr-code', Icon: QrCode, group: 'contact', label: "QR-код", keywords: "ссылка сканировать код" },
  { key: 'map-pin', Icon: MapPin, group: 'place', label: "Адрес", keywords: "карта точка где находимся филиал" },
  { key: 'map', Icon: Map, group: 'place', label: "Карта", keywords: "маршрут как добраться схема" },
  { key: 'building2', Icon: Building2, group: 'place', label: "Медцентр", keywords: "здание клиника филиал офис" },
  { key: 'home', Icon: Home, group: 'place', label: "Дом", keywords: "на дому выезд домой" },
  { key: 'navigation', Icon: Navigation, group: 'place', label: "Маршрут", keywords: "навигатор проложить дорогу" },
  { key: 'car', Icon: Car, group: 'place', label: "Машина", keywords: "парковка приехать автомобиль" },
  { key: 'bus', Icon: Bus, group: 'place', label: "Транспорт", keywords: "автобус доехать остановка" },
  { key: 'parking-circle', Icon: ParkingCircle, group: 'place', label: "Парковка", keywords: "машина стоянка бесплатно" },
  { key: 'user', Icon: User, group: 'people', label: "Человек", keywords: "пациент профиль личный кабинет" },
  { key: 'users', Icon: Users, group: 'people', label: "Семья", keywords: "группа люди все вместе" },
  { key: 'user-check', Icon: UserCheck, group: 'people', label: "Проверено", keywords: "пациент подтверждён врач принял" },
  { key: 'user-plus', Icon: UserPlus, group: 'people', label: "Новый пациент", keywords: "регистрация добавить впервые" },
  { key: 'heart-handshake', Icon: HeartHandshake, group: 'people', label: "Забота", keywords: "помощь поддержка отношение" },
  { key: 'graduation-cap', Icon: GraduationCap, group: 'people', label: "Опыт", keywords: "образование учёба квалификация врач" },
  { key: 'award', Icon: Award, group: 'people', label: "Награда", keywords: "качество достижение лучший" },
  { key: 'badge-check', Icon: BadgeCheck, group: 'people', label: "Подтверждено", keywords: "проверено гарантия официально" },
  { key: 'star', Icon: Star, group: 'people', label: "Звезда", keywords: "отзыв оценка рейтинг лучшее" },
  { key: 'thumbs-up', Icon: ThumbsUp, group: 'people', label: "Нравится", keywords: "отзыв рекомендация одобрение" },
  { key: 'smile', Icon: Smile, group: 'people', label: "Улыбка", keywords: "довольный пациент настроение" },
  { key: 'crown', Icon: Crown, group: 'people', label: "Премиум", keywords: "лучший вип корона" },
  { key: 'file-text', Icon: FileText, group: 'docs', label: "Документ", keywords: "справка заключение бумага" },
  { key: 'clipboard-list', Icon: ClipboardList, group: 'docs', label: "Список", keywords: "перечень чек-лист подготовка" },
  { key: 'clipboard-check', Icon: ClipboardCheck, group: 'docs', label: "Готово", keywords: "проверено выполнено список" },
  { key: 'file-check', Icon: FileCheck, group: 'docs', label: "Результат", keywords: "анализ готов заключение справка" },
  { key: 'book-open', Icon: BookOpen, group: 'docs', label: "Памятка", keywords: "инструкция статья читать" },
  { key: 'folder', Icon: Folder, group: 'docs', label: "Карта пациента", keywords: "папка история документы" },
  { key: 'download', Icon: Download, group: 'docs', label: "Скачать", keywords: "загрузить файл результат" },
  { key: 'printer', Icon: Printer, group: 'docs', label: "Распечатать", keywords: "печать бумага справка" },
  { key: 'check', Icon: Check, group: 'misc', label: "Галочка", keywords: "да готово выполнено пункт" },
  { key: 'check-circle2', Icon: CheckCircle2, group: 'misc', label: "Галочка в круге", keywords: "готово да подтверждено пункт" },
  { key: 'info', Icon: Info, group: 'misc', label: "Важно", keywords: "информация внимание примечание" },
  { key: 'shield-check', Icon: ShieldCheck, group: 'misc', label: "Безопасно", keywords: "защита гарантия качество стерильно" },
  { key: 'shield', Icon: Shield, group: 'misc', label: "Защита", keywords: "безопасность гарантия" },
  { key: 'zap', Icon: Zap, group: 'misc', label: "Быстро", keywords: "молния срочно скорость" },
  { key: 'lightbulb', Icon: Lightbulb, group: 'misc', label: "Совет", keywords: "идея лампочка подсказка" },
  { key: 'target', Icon: Target, group: 'misc', label: "Точность", keywords: "цель мишень результат" },
  { key: 'trending-up', Icon: TrendingUp, group: 'misc', label: "Рост", keywords: "график улучшение динамика" },
  { key: 'sparkles', Icon: Sparkles, group: 'misc', label: "Новинка", keywords: "блеск новое особенное" },
  { key: 'rocket', Icon: Rocket, group: 'misc', label: "Старт", keywords: "запуск новое открытие ракета" },
  { key: 'leaf', Icon: Leaf, group: 'misc', label: "Природа", keywords: "лист эко натурально здоровье" },
  { key: 'sun', Icon: Sun, group: 'misc', label: "Солнце", keywords: "лето день свет" },
  { key: 'snowflake', Icon: Snowflake, group: 'misc', label: "Зима", keywords: "снежинка холод сезон" },
  { key: 'flame', Icon: Flame, group: 'misc', label: "Горячее", keywords: "огонь популярное акция" },
  { key: 'truck', Icon: Truck, group: 'misc', label: "Доставка", keywords: "привезём выезд машина" },
  { key: 'package', Icon: Package, group: 'misc', label: "Комплекс", keywords: "набор пакет коробка программа" },
  { key: 'search', Icon: Search, group: 'misc', label: "Поиск", keywords: "найти лупа подобрать" },
  { key: 'camera', Icon: Camera, group: 'misc', label: "Фото", keywords: "снимок камера" },
  { key: 'video', Icon: Video, group: 'misc', label: "Видео", keywords: "запись ролик онлайн" },
  { key: 'play', Icon: Play, group: 'misc', label: "Смотреть", keywords: "видео запуск плей" },
  { key: 'lock', Icon: Lock, group: 'misc', label: "Конфиденциально", keywords: "замок тайна защита данных" },
  { key: 'key', Icon: Key, group: 'misc', label: "Доступ", keywords: "ключ вход код" },
  { key: 'flag', Icon: Flag, group: 'misc', label: "Отметка", keywords: "флаг важное этап" },
  { key: 'compass', Icon: Compass, group: 'misc', label: "Направление", keywords: "компас выбор путь" },
  { key: 'gem', Icon: Gem, group: 'misc', label: "Ценное", keywords: "камень премиум редкое" },
  { key: 'coffee', Icon: Coffee, group: 'misc', label: "Уют", keywords: "кофе отдых ожидание" },
];

export const ICON_BY_KEY = EMAIL_ICONS.reduce((acc, i) => { acc[i.key] = i; return acc; }, {});
